name: DangerJS Pull Request review

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:
  push:
    branches:
      - !master

permissions:
  actions: read
  checks: read
  contents: read
  issues: write
  pull-requests: write
  security-events: read
  statuses: write

jobs:
  danger-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/dangerjs
    steps:
    - uses: actions/checkout@v3

    - name: Setup NodeJS environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
        cache-dependency-path: .github/dangerjs/package-lock.json

    - name: Get Node version
      run: node --version

    - name: Get NPM version
      run: npm --version

    - name: Install DangerJS dependencies
      run: npm install

    - name: Transpile Dangerfile TS to JS
      run: npx tsc

    - name: Run DangerJS
      run: npx danger ci --failOnErrors -v
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: .github/dangerjs/dist
